'TWITTER_KEY' : 'dOb65vOsUwIO20xu5Yl7fQ'
'TWITTER_SECRET' : 'MpvcR77usa1CrhOUkZyzaX1m9pq2l1ugoMuncLdqs'
'OAUTH_TOKEN' : '1007361553-0VMHpkYhMW6Bm5PCw8tZaCDULxe1leIODiImIZV'
'OAUTH_SECRET' : 'IetM4UjyukLTEdOcAhhuj3sSsSgVkC0639SnZHEWnO8'
